### ISSUE TITLE
Smearing with TSR 

### ISSUE THREAD

**Issue by ErenBalatkan** [LukasFratzl/TurboSequence#2]
Greetings,

Thank you for sharing this amazing plugin!

I noticed that in UE5.4 Update patch notes, it states that Motion Vectors are made accurate with the update. However, I'm getting smearing artifacts on UE5.4 when TSR is enabled, which generally happens when Motion Vectors aren't generated. Issue disappears when TSR is disabled.

I was wondering if this is a known limitation, or something is wrong with my setup? I don't have anything special on my setup and am getting same issue on Demo Map as well. 

Smearing is pretty hard to notice at ScreenPercentage set to 100, but more noticeable on 50

**Comment by LukasFratzl** [comment]
Hey,

I'm not sure if this artefacts are motion vectors or something different, could be wrong reflections as well.... As well as wrong motion vectors

But these artefacts are definitely noticeable, it is not just your setup ....

I have so much going on right now, so please don't count on a change on my side in near future!

**Comment by ErenBalatkan** [comment]
No worries! Thank you again for the incredible work

**Comment by LukasFratzl** [comment]
Hey, it should be fixed with this commit [Fixed Motion vectors, special thanks to @ dantreble finding the fix
](https://github.com/LukasFratzl/TurboSequence/commit/9852a495915357472b228ad8048183ccd307cf92)

I will add it into the 5.5 release, have a nice day!
